[general]

[global]

[internal]
; Внутренние пользователи
#include users_extensions.conf

; Голосовое меню
exten => 01,1,Goto(voice_menu,s,1)

[voice_menu]
exten => s,1,Background(basic-pbx-ivr-main)
   same => n,WaitExten(8)
   same => n,Background(vm-repeat)
   same => n,WaitExten(5)
   same => n,Playback(goodbye)
   same => n,Hangup()

exten => _X,1,Playback(digits/${EXTEN})  ; Воспроизведение цифры
   same => n,Goto(handle_input,${EXTEN},1)  ; Передача нажатой цифры в handle_input

[handle_input]
exten => 1,1,Goto(sales_department,1,2)  ; Перенаправление в отдел продаж
exten => 2,1,Goto(technical_support,1,2)  ; Перенаправление в техподдержку
exten => 3,1,Goto(finance_department,1,2)  ; Перенаправление в финансовый отдел
exten => 4,1,Goto(employee_catalogist,1,2)  ; Перенаправление в каталог сотрудников
exten => 5,1,Goto(internal,01,1)  ; Возврат в главное меню
exten => 0,1,Goto(queue_operators,1,2)  ; Перенаправление в очередь операторов
exten => *,1,Goto(internal,01,1)  ; Возврат в главное меню

[sales_department]
exten => 1,1,Answer()
   same => n,Background(pm-invalid-option&vm-starmain)
   same => n,WaitExten(5)
   same => n,Playback(goodbye)
   same => n,Hangup()

exten => *,1,Goto(internal,01,1)  ; Возвращаемся в главное меню по нажатию *

[technical_support]
exten => 1,1,Answer()
   same => n,Background(pm-invalid-option&vm-starmain)
   same => n,WaitExten(5)
   same => n,Playback(goodbye)
   same => n,Hangup()

exten => *,1,Goto(internal,01,1)  ; Возвращаемся в главное меню по нажатию *

[finance_department]
exten => 1,1,Answer()
   same => n,Background(pm-invalid-option&vm-starmain)
   same => n,WaitExten(5)
   same => n,Playback(goodbye)
   same => n,Hangup()

exten => *,1,Goto(internal,01,1)  ; Возвращаемся в главное меню по нажатию *

[employee_catalogist]
exten => 1,1,Answer()
   same => n,Background(pm-invalid-option&vm-starmain)
   same => n,WaitExten(5)
   same => n,Playback(goodbye)
   same => n,Hangup()

exten => *,1,Goto(internal,01,1)  ; Возвращаемся в главное меню по нажатию *

[queue_operators]
exten => 1,1,Answer()
   same => n,Playback(conf-now-recording)
   same => n,Queue(operators,,,,,,,sub_macro1)
   same => n,Hangup()

[sub_macro1]
exten => s,1,Verbose(Call macro 1)
   same => n,Set(connectedlinetemp=${CUT(CHANNEL,/,2)})
   same => n,Set(connectedline=${CUT(connectedlinetemp,-,1)})
   same => n,Set(fname=${STRFTIME(${EPOCH},,%Y-%m-%d-%H-%M-%S)}-${CONNECTEDLINE(number)}-${connectedline}-${UNIQUEID})
   same => n,Set(fname_folder=${STRFTIME(${EPOCH},,%Y)}/${STRFTIME(${EPOCH},,%m)}/${STRFTIME(${EPOCH},,%d)})
   same => n,Set(monitor_folder=/var/spool/asterisk/monitor)
   same => n,Set(MIXMONITOR_FILENAME_SOX=${fname_folder}/${fname}.wav)
   same => n,MixMonitor(,r(${fname_folder}/${fname}-r.wav)t(${fname_folder}/${fname}-t.wav),sox -M ${monitor_folder}/${fname_folder}/${fname}-r.wav ${monitor_folder}/${fname_folder}/${fname}-t.wav ${monitor_folder}/${fname_folder}/${fname}.wav && rm ${monitor_folder}/${fname_folder}/${fname}-r.wav ${monitor_folder}/${fname_folder}/${fname}-t.wav)
   same => n,Return()

