; PJSIP Configuration Samples and Quick Reference
;

; UDP transport behind NAT
;
[transport-udp-nat]
type=transport
protocol=udp
bind=0.0.0.0
local_net=127.0.0.0/24

; заменить на свои адреса
;local_net=172.17.0.0/24
external_media_address=90.156.206.67
external_signaling_address=90.156.206.67

#include users.conf
