; PJSIP Configuration Samples and Quick Reference
;

; UDP transport behind NAT
;
[transport-udp-nat]
type=transport
protocol=udp
bind=0.0.0.0
local_net=127.0.0.0/24

; заменить на свои адреса
;local_net=172.17.0.0/24
external_media_address=90.156.206.67
external_signaling_address=90.156.206.67

[transport-wss]
type=transport
protocol=wss
bind=0.0.0.0
; All other transport parameters are ignored for wss transports.
external_media_address=90.156.206.67
external_signaling_address=90.156.206.67
;cert_file=/etc/asterisk/keys/ca.crt
;priv_key_file=/etc/asterisk/keys/ca.key

#include users.conf

[200]
type=endpoint
context=internal
disallow=all
allow=opus,alaw,ulaw
dtls_auto_generate_cert=yes
webrtc=yes
; Setting webrtc=yes is a shortcut for setting the following options:
; use_avpf=yes
; media_encryption=dtls
; dtls_verify=fingerprint
; dtls_setup=actpass
; ice_support=yes
; media_use_received_transport=yes
; rtcp_mux=yes
media_address=90.156.206.67
direct_media=no
language=ru
auth=200
aors=200

[200]
type=auth
auth_type=userpass
username=penart
password=panama

[200](internal-aor)


