
; Пользователь: администратор, Отдел: admins, Телефон: 100
exten => 100,1,Dial(PJSIP/admin)
same => n,Hangup()

; Пользователь: user1, Отдел: операторы, Телефон: 101
exten => 101,1,Dial(PJSIP/user1)
same => n,Hangup()

; Пользователь: user2, Отдел: операторы, Телефон: 102
exten => 102,1,Dial(PJSIP/user2)
same => n,Hangup()

; Пользователь: Кузугашев С.В., Отдел: операторы, Телефон: 707
exten => 707,1,Dial(PJSIP/Forlein)
same => n,Hangup()
