
#include users_template.conf


; Пользователь: администратор, Отдел: admins, Телефон: 100

[100](internal-endpoint)
auth=100
aors=100

[100](internal-auth)
username=admin
md5_cred=48fa3f4abedfaa10942b2ae96b77961d

[100](internal-aor)

; Пользователь: Сидоров И.В., Отдел: operators, Телефон: 102

[102](internal-endpoint)
auth=102
aors=102

[102](internal-auth)
username=user2
md5_cred=c664a55b5d6ff1268740d85ea8d83aa6

[102](internal-aor)

; Пользователь: Кузугашев В.И., Отдел: operators, Телефон: 101

[101](internal-endpoint)
auth=101
aors=101

[101](internal-auth)
username=user1
md5_cred=aaf4b2aa7dcc971d16c554705cb2881f

[101](internal-aor)
