
; Пользователь: администратор, Отдел: admins, Телефон: 100
exten => 100,1,Dial(PJSIP/100)
same => n,Hangup()

; Пользователь: Сидоров И.В., Отдел: operators, Телефон: 102
exten => 102,1,Dial(PJSIP/102)
same => n,Hangup()

; Пользователь: user1, Отдел: operators, Телефон: 101
exten => 101,1,Dial(PJSIP/101)
same => n,Hangup()
