[internal-aor](!)
type=aor
max_contacts=2
qualify_frequency=60

[internal-endpoint](!)
type=endpoint
context=internal
disallow=all
allow=!all,alaw,ulaw
transport=transport-udp-nat
media_address = 192.168.1.101 ; требуется задать внешний IP адресс
direct_media=no
rewrite_contact=yes
rtp_symmetric=yes
language=ru

[internal-auth](!)
type=auth
auth_type=md5