
; Пользователь: администратор, Отдел: Администрация, Телефон: 00000000000
exten => 00000000000,1,Dial(PJSIP/admin)
same => n,Hangup()

; Пользователь: Иванов Иван Иванович, Отдел: Отдел продаж, Телефон: 101
exten => 101,1,Dial(PJSIP/user1)
same => n,Hangup()

; Пользователь: Сидоров Иван Петрович, Отдел: Отдел продаж, Телефон: 101
exten => 101,1,Dial(PJSIP/user2)
same => n,Hangup()

; Пользователь: Сидоров Иван Петрович, Отдел: Отдел продаж, Телефон: 103
exten => 103,1,Dial(PJSIP/user3)
same => n,Hangup()

; Пользователь: Сидоров Иван Петрович, Отдел: Отдел продаж, Телефон: 104
exten => 104,1,Dial(PJSIP/user4)
same => n,Hangup()
