[internal-aor](!)
type=aor
max_contacts=1
qualify_frequency=60
remove_existing=yes

[internal-endpoint](!)
type=endpoint
context=internal
disallow=all
allow=opus,alaw,ulaw,h264,vp8
transport=transport-udp-nat
media_address=asterisk
direct_media=no
rewrite_contact=yes
rtp_symmetric=yes
language=ru

[internal-auth](!)
type=auth
auth_type=md5
