
#include users_template.conf


; Пользователь: администратор, Отдел: Администрация, Телефон: 00000000000

[admin](internal-endpoint)
auth=admin
aors=admin

[admin](internal-auth)
username=admin
md5_cred=

[admin](internal-aor)

; Пользователь: Иванов Иван Иванович, Отдел: Отдел продаж, Телефон: 101

[user1](internal-endpoint)
auth=user1
aors=user1

[user1](internal-auth)
username=user1
md5_cred=ef48f2fb5196b5d10b7b57803b7ff257

[user1](internal-aor)

; Пользователь: Сидоров Иван Петрович, Отдел: Отдел продаж, Телефон: 102

[user2](internal-endpoint)
auth=user2
aors=user2

[user2](internal-auth)
username=user2
md5_cred=808843607fe80ca29d449ac8a617135a

[user2](internal-aor)

; Пользователь: Сидоров Иван Петрович, Отдел: Отдел продаж, Телефон: 103

[user3](internal-endpoint)
auth=user3
aors=user3

[user3](internal-auth)
username=user3
md5_cred=04ff3093e7b1648fb45b290494974b6d

[user3](internal-aor)

; Пользователь: Сидоров Иван Петрович, Отдел: Отдел продаж, Телефон: 104

[user4](internal-endpoint)
auth=user4
aors=user4

[user4](internal-auth)
username=user4
md5_cred=c842584b50dfe58fe8a359816586c341

[user4](internal-aor)
