[general]
enabled=yes           ; Включаем встроенный веб-сервер
bindaddr=0.0.0.0      ; Слушаем все сетевые интерфейсы
bindport=8088         ; Порт для прослушивания
prefix=               ; Префикс для URL
;staticdir=/var/lib/asterisk/static-http,/var/spool/asterisk/monitor          ; Директория для статического контента
redirect= /monitor /var/spool/asterisk/monitor                          ; Корневая директория для динамического контента
enable_static=yes       ; Разрешаем обслуживание статического контента
realm=Asterisk HTTP     ; Область для HTTP-аутентификации
enable_status=yes
