[operator]
member => PJSIP/oper1
member => PJSIP/oper2

;member => Local/oper1@internal/n
;member => Local/oper2@internal/n

;monitor-format = wav
;monitor-type = MixMonitor
;mixmonitor = ${MONITOR_FILENAME}

announce-frequency=1 ; как часто будет повторяться ожидающему сообщения о его номере в очереди (0-выкл. это сообщение)
announce-holdtime=yes ; сообщать о времени ожидания
announce-position=yes ; сообщать номер в очереди
autofill=no ; опция версии 1.4, направить звонок всем ожидающим операторам (в зависимости от стратегии звонков)
eventmemberstatus=no ; по умолчание = нет, если да, то при изменении статуса агента очереди информация будет передана в AMI
eventwhencalled=no ; по умолчание = нет, если да, то следующие события будут сформированы для AgentCalled, AgentDump, AgentConnect и AgentComplete
joinempty=yes ; с помощью этой функции можно определить, состоит ли агент в этой очереди и может ли он к ней присоединиться
leavewhenempty=no ; параметр возможности удаления из очереди агентов
maxlen=0 ; определение максимального количества входящих звонков (0-неограничено)
memberdelay=0 ; пауза (в сек) между вызовами 1 и 2 оператора и т. д.
penaltymemberslimit=0 ; выставление приоритета для агентов очереди, агент с приоритетом «1» не сможет принять звонок пока есть доступные агенты с приоритетом «0»
periodic-announce-frequency=10 ; промежутки времени ожидания, абоненту будет проигрываться определенное голосовое сообщение
queue-callswaiting=queue-callswaiting ; silence/1 ; описания звуковых файлов, для анонса абоненту его позиции в очереди
queue-thereare=queue-thereare ; silence/1 ; описания звуковых файлов, для анонса абоненту его позиции в очереди
queue-youarenext=queue-youarenext ;silence/1 ; описания звуковых файлов, для анонса абоненту его позиции в очереди
reportholdtime=yes ; функция, которая сообщает принимающему звонок агенту о том, сколько времени данный абонент находился в очереди
retry=8 ; количество секунд, через которое будет повторяться звонок на все телефоны
servicelevel=60 ; опция используется для статистики об уровне обслуживания
strategy=ringall ;rrmemory ;ringall ; стратегия дозвона
timeout=5 ; время (в сек), в течение которого вызов будет поступать на телефон агента очереди
timeoutpriority=app ; параметр, отвечающий за разграничение таймаутов оператора и очереди, если выбран «app» — приоритет получает таймаут очереди, conf — приоритет получает таймаут оператора
timeoutrestart=no ; если параметр установлен в значение yes, тогда значение таймаута для агента будет сбрасываться, если от него будет получен сигнал BUSY или CONGESTION
weight=0 ; вызов, ожидающий в очереди с более высоким приоритетом, будет обработан одним из первых
wrapuptime=0 ; это значение минимального промежутка времени, с момента, когда работа с абонентом завершена и до того, как участник обработки может принять новый вызов из очереди