
; Пользователь: Иван Иванов, Отдел: office, Телефон: 100
exten => 100,1,Dial(PJSIP/user1)
same => n,Hangup()

; Пользователь: Петрова Мария, Отдел: operators, Телефон: 101
exten => 101,1,Dial(PJSIP/user2)
same => n,Hangup()

; Пользователь: Сидоров Алексей, Отдел: operators, Телефон: 102
exten => 102,1,Dial(PJSIP/user3)
same => n,Hangup()
