
; Пользователь: Иван Иванов, Отдел: operators, Телефон: 100

[useruser1](internal-endpoint)
auth=useruser1
aors=useruser1

[useruser1](internal-auth)
username=user1
password=789123

[useruser1](internal-aor)

; Пользователь: Петрова Мария, Отдел: operators, Телефон: 101

[useruser2](internal-endpoint)
auth=useruser2
aors=useruser2

[useruser2](internal-auth)
username=user2
password=456987

[useruser2](internal-aor)

; Пользователь: Сидоров Алексей, Отдел: operators, Телефон: 102

[useruser3](internal-endpoint)
auth=useruser3
aors=useruser3

[useruser3](internal-auth)
username=user3
password=654321

[useruser3](internal-aor)
